export const privateRoutes: string[] = [
    '/dashboard',
    '/dashboard/diner',
    '/dashboard/restaurant',
    '/portal',
    '/post-event',
    '/talent-onboarding',
    '/influencer-onboarding',
    '/company-profile',
    '/company-success',
    '/talent-success',
    '/event-success',
    '/events',
    '/messages',
    '/event', 
    '/add-role',
    '/message',
    '/create-message',
    '/message-success',
    '/role',
    '/connect-social',
    '/profile',
    '/portfolio',
    '/settings',
    '/auditions',
    '/admin',
    '/talent',
    '/apply',
    '/applications',
    '/assistant',
    '/receipt',
    '/menu-analysis',
  ];
  
  export const publicRoutes: string[] = [
    '/',
    '/login',
    '/register/diner',
    '/register/restaurant',
    '/otp',
    '/forgot',
    '/reset',
    '/forgot-success',
    '/help',
    '/pricing',
    '/termsofservice',
    '/privacypolicy'
  ];
  
  export const hybridRoutes: string[] = [
    '/about',
    '/jobs',
    '/talent',
    '/contact',
    '/terms-of-service',
    '/privacy-policy',
    '/terms-and-conditions'
  ];